# Generated by Django 4.2.3 on 2023-09-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_servicio_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='detalle',
            new_name='autor',
        ),
    ]
