# Generated by Django 4.2.3 on 2023-09-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(default='correo@example.com', max_length=254),
        ),
    ]
